# Generated by Django 4.2.23 on 2025-08-05 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Послуга', 'verbose_name_plural': 'Послуги'},
        ),
        migrations.AlterModelOptions(
            name='servicefeature',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Особливість послуги', 'verbose_name_plural': 'Особливості послуг'},
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, upload_to='services/icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg'])], verbose_name='Іконка'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Рекомендована'),
        ),
        migrations.AlterField(
            model_name='service',
            name='main_image',
            field=models.ImageField(upload_to='services/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Головне зображення'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active', 'is_featured', 'order'], name='services_se_is_acti_39af20_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active', 'order'], name='services_se_is_acti_dbc8d8_idx'),
        ),
        migrations.AddIndex(
            model_name='servicefeature',
            index=models.Index(fields=['service', 'order'], name='services_se_service_dbccc2_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicefeature',
            constraint=models.UniqueConstraint(fields=('service', 'order'), name='unique_service_feature_order'),
        ),
    ]
