# Generated by Django 5.2.4 on 2025-07-22 07:37

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Історія компанії')),
                ('history_text_uk', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Історія компанії')),
                ('history_text_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Історія компанії')),
                ('mission_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Місія')),
                ('mission_text_uk', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Місія')),
                ('mission_text_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Місія')),
                ('values_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Цінності')),
                ('values_text_uk', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Цінності')),
                ('values_text_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Цінності')),
                ('social_responsibility', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Соціальна відповідальність')),
                ('social_responsibility_uk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Соціальна відповідальність')),
                ('social_responsibility_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Соціальна відповідальність')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': "Сторінка 'Про нас'",
                'verbose_name_plural': "Сторінка 'Про нас'",
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('title_uk', models.CharField(max_length=200, null=True, verbose_name='Назва')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('description_uk', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('image', models.ImageField(upload_to='certificates/', verbose_name='Зображення')),
                ('issued_date', models.DateField(verbose_name='Дата видачі')),
                ('issuing_organization', models.CharField(max_length=200, verbose_name='Організація, що видала')),
                ('certificate_url', models.URLField(blank=True, verbose_name='Посилання на сертифікат')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Сертифікат',
                'verbose_name_plural': 'Сертифікати',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(default='Професійний одяг', help_text='Перший рядок заголовка Hero секції', max_length=200, verbose_name='Основний заголовок')),
                ('sphere_title', models.CharField(default='кожної сфери', help_text="Другий рядок заголовка (після 'для')", max_length=200, verbose_name='Заголовок сфери')),
                ('sphere_title_uk', models.CharField(default='кожної сфери', help_text="Другий рядок заголовка (після 'для')", max_length=200, null=True, verbose_name='Заголовок сфери')),
                ('sphere_title_en', models.CharField(default='кожної сфери', help_text="Другий рядок заголовка (після 'для')", max_length=200, null=True, verbose_name='Заголовок сфери')),
                ('subtitle', models.TextField(help_text='Опис під заголовком Hero секції', max_length=500, verbose_name='Підзаголовок')),
                ('subtitle_uk', models.TextField(help_text='Опис під заголовком Hero секції', max_length=500, null=True, verbose_name='Підзаголовок')),
                ('subtitle_en', models.TextField(help_text='Опис під заголовком Hero секції', max_length=500, null=True, verbose_name='Підзаголовок')),
                ('primary_button_text', models.CharField(default='Наші проєкти', help_text='Текст для головної кнопки дії', max_length=100, verbose_name='Текст основної кнопки')),
                ('primary_button_text_uk', models.CharField(default='Наші проєкти', help_text='Текст для головної кнопки дії', max_length=100, null=True, verbose_name='Текст основної кнопки')),
                ('primary_button_text_en', models.CharField(default='Наші проєкти', help_text='Текст для головної кнопки дії', max_length=100, null=True, verbose_name='Текст основної кнопки')),
                ('secondary_button_text', models.CharField(default='Дізнатися більше', help_text='Текст для другорядної кнопки', max_length=100, verbose_name='Текст другорядної кнопки')),
                ('secondary_button_text_uk', models.CharField(default='Дізнатися більше', help_text='Текст для другорядної кнопки', max_length=100, null=True, verbose_name='Текст другорядної кнопки')),
                ('secondary_button_text_en', models.CharField(default='Дізнатися більше', help_text='Текст для другорядної кнопки', max_length=100, null=True, verbose_name='Текст другорядної кнопки')),
                ('years_experience', models.CharField(default='5+', help_text="Кількість років досвіду (наприклад: '5+', '10')", max_length=10, verbose_name='Роки досвіду')),
                ('satisfied_clients', models.CharField(default='50+', help_text="Кількість задоволених клієнтів (наприклад: '50+', '100')", max_length=10, verbose_name='Задоволені клієнти')),
                ('completed_projects', models.IntegerField(default=100, help_text='Кількість завершених проєктів (число)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Завершені проєкти')),
                ('employees_count', models.IntegerField(default=20, help_text='Кількість співробітників компанії', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кількість співробітників')),
                ('additional_info', models.TextField(blank=True, help_text='Додатковий текст для відображення в Hero секції', verbose_name='Додаткова інформація')),
                ('meta_title', models.CharField(blank=True, help_text='SEO заголовок сторінки', max_length=60, verbose_name='Meta заголовок')),
                ('meta_description', models.TextField(blank=True, help_text='SEO опис сторінки', max_length=160, verbose_name='Meta опис')),
                ('is_active', models.BooleanField(default=True, help_text='Чи активна ця версія головної сторінки', verbose_name='Активна')),
                ('show_featured_services', models.BooleanField(default=True, help_text='Показувати блок рекомендованих послуг в Hero секції', verbose_name='Показувати рекомендовані послуги')),
                ('featured_services_count', models.IntegerField(default=3, help_text='Скільки рекомендованих послуг показувати', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Кількість рекомендованих послуг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Головна сторінка',
                'verbose_name_plural': 'Головна сторінка',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('title_uk', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('description_uk', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('image', models.ImageField(upload_to='production/', verbose_name='Зображення')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендоване')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Фото виробництва',
                'verbose_name_plural': 'Фото виробництва',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('name_uk', models.CharField(max_length=100, null=True, verbose_name="Ім'я")),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name="Ім'я")),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('position_uk', models.CharField(max_length=100, null=True, verbose_name='Посада')),
                ('position_en', models.CharField(max_length=100, null=True, verbose_name='Посада')),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Біографія')),
                ('bio_uk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Біографія')),
                ('bio_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Біографія')),
                ('photo', models.ImageField(upload_to='team/', verbose_name='Фото')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Електронна пошта')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_management', models.BooleanField(default=False, verbose_name='Керівництво')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Член команди',
                'verbose_name_plural': 'Команда',
                'ordering': ['order', 'name'],
            },
        ),
    ]
