# Generated by Django 5.2.4 on 2025-07-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='main_title_en',
            field=models.CharField(default='Професійний одяг', help_text='Перший рядок заголовка Hero секції', max_length=200, null=True, verbose_name='Основний заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='main_title_uk',
            field=models.CharField(default='Професійний одяг', help_text='Перший рядок заголовка Hero секції', max_length=200, null=True, verbose_name='Основний заголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sphere_title',
            field=models.CharField(default='кожної сфери', help_text='Другий рядок заголовка', max_length=200, verbose_name='Заголовок сфери'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sphere_title_en',
            field=models.CharField(default='кожної сфери', help_text='Другий рядок заголовка', max_length=200, null=True, verbose_name='Заголовок сфери'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sphere_title_uk',
            field=models.CharField(default='кожної сфери', help_text='Другий рядок заголовка', max_length=200, null=True, verbose_name='Заголовок сфери'),
        ),
    ]
