# Generated by Django 5.2.4 on 2025-07-23 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_homepage_main_title_en_homepage_main_title_uk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='homepage',
            field=models.ForeignKey(blank=True, help_text='Чи показувати цього члена команди на головній сторінці', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='content.homepage', verbose_name='Головна сторінка'),
        ),
    ]
