# Generated by Django 5.2.4 on 2025-07-23 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_teammember_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='homepage',
            field=models.ForeignKey(blank=True, help_text='Чи показувати цього члена команди на головній сторінці', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teammember_set', to='content.homepage', verbose_name='Головна сторінка'),
        ),
    ]
