# Generated by Django 5.2.4 on 2025-07-23 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_teammember_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='homepage',
            field=models.ForeignKey(blank=True, help_text='Чи показувати цей сертифікат на головній сторінці', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_set', to='content.homepage', verbose_name='Головна сторінка'),
        ),
        migrations.AddField(
            model_name='productionphoto',
            name='homepage',
            field=models.ForeignKey(blank=True, help_text='Чи показувати це фото на головній сторінці', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productionphoto_set', to='content.homepage', verbose_name='Головна сторінка'),
        ),
    ]
