# Generated by Django 5.2.4 on 2025-07-25 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_certificate_homepage_productionphoto_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'ordering': ['-updated_at', 'id'], 'verbose_name': "Сторінка 'Про нас'", 'verbose_name_plural': "Сторінка 'Про нас'"},
        ),
    ]
