# Generated by Django 5.2.4 on 2025-07-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ['order', 'city'], 'verbose_name': 'Офіс/Фабрика', 'verbose_name_plural': 'Офіси/Фабрики'},
        ),
        migrations.AddField(
            model_name='office',
            name='city',
            field=models.CharField(default=0, max_length=100, verbose_name='Місто'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='city_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='office',
            name='city_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Місто'),
        ),
    ]
