# Generated by Django 4.2.23 on 2025-08-05 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-created_at', 'id'], 'verbose_name': 'Заявка на вакансію', 'verbose_name_plural': 'Заявки на вакансії'},
        ),
        migrations.AlterModelOptions(
            name='jobposition',
            options={'ordering': ['-is_urgent', '-created_at', 'id'], 'verbose_name': 'Вакансія', 'verbose_name_plural': 'Вакансії'},
        ),
        migrations.AlterModelOptions(
            name='workplacephoto',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Фото робочого місця', 'verbose_name_plural': 'Фото робочих місць'},
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Телефон має бути у форматі: '+999999999'. До 15 цифр дозволено.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='Резюме'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='is_urgent',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Терміново'),
        ),
        migrations.AlterField(
            model_name='workplacephoto',
            name='image',
            field=models.ImageField(upload_to='workplace/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='workplacephoto',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['position', '-created_at'], name='jobs_jobapp_positio_3891d7_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['is_reviewed', '-created_at'], name='jobs_jobapp_is_revi_5adec8_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposition',
            index=models.Index(fields=['is_active', '-created_at'], name='jobs_jobpos_is_acti_1ec198_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposition',
            index=models.Index(fields=['is_urgent', '-created_at'], name='jobs_jobpos_is_urge_b0af97_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposition',
            index=models.Index(fields=['employment_type', 'is_active'], name='jobs_jobpos_employm_34ec1b_idx'),
        ),
        migrations.AddIndex(
            model_name='workplacephoto',
            index=models.Index(fields=['is_active', 'order'], name='jobs_workpl_is_acti_5367dd_idx'),
        ),
    ]
