# Generated by Django 5.2.4 on 2025-07-25 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerinquiry',
            options={'ordering': ['-created_at', 'id'], 'verbose_name': 'Запит партнера', 'verbose_name_plural': 'Запити партнерів'},
        ),
        migrations.AlterModelOptions(
            name='partnershipinfo',
            options={'ordering': ['-updated_at', 'id'], 'verbose_name': 'Інформація для партнерів', 'verbose_name_plural': 'Інформація для партнерів'},
        ),
        migrations.AlterModelOptions(
            name='workstage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Етап роботи', 'verbose_name_plural': 'Етапи роботи'},
        ),
    ]
